# Generated by Django 4.2.5 on 2023-10-21 05:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('visibility', models.CharField(choices=[('pr', 'private'), ('pu', 'public')], default='pr', max_length=2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('assignUsers', models.ManyToManyField(blank=True, related_name='assignBoards', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('tag', models.CharField(max_length=150, verbose_name='tag')),
                ('notificationsStatus', models.CharField(choices=[('w', 'w'), ('nw', 'nw')], default='nw', max_length=2)),
                ('listId', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('deadLine', models.DateTimeField(auto_now_add=True, verbose_name='deadLine')),
                ('assignUsers', models.ManyToManyField(blank=True, related_name='assignCards', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsCreate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300, verbose_name='notification message')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('notificationCard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsCard', to='trello.card')),
                ('notificationUsers', models.ManyToManyField(blank=True, related_name='notificationsUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('boardId', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='trello.board')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('cardId', models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('replyCommentId', models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trello.card')),
                ('replyComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trello.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writerComments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-writedAt'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.list'),
        ),
    ]
