# Generated by Django 4.2.5 on 2023-10-15 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('listId', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsCreator', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsList', to='trello.list')),
            ],
        ),
    ]
