# Generated by Django 4.2.5 on 2023-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('pr', 'private'), ('pu', 'public')], default='pr', max_length=2),
        ),
    ]
